= Cloud Native Application Architectures with Spring and Cloud Foundry

Student Guide

== Instructor Details

Sergiu Bodiu (@mstine) +
Principal Enginedreamsergiu / Senior Solution Architect - Pivotal +
sbodiu@pivotal.io


== Schedule

This is _loose_ schedule for the two days. We will adjust as necessary based on our pace through the material.

The lectures for this class are intentionally very light and are only intended to set the stage for the hands-on labs.
The overwhelming majority of our time will be spent engaging with the technology directly!

NOTE: We will be updating the course materials throughout the class. You will need to have the materials cloned and track the `citi` branch.

This can be accomplished as follows:

----
$ git clone https://github.com/sbodiu-pivotal/cloud-lab
----

=== Day One

8:00 AM - 9:30 AM:: *Session 1:* _Cloud-Native Architecture Overview and Building Twelve-Factor Apps with Spring Boot_
9:30 AM - 10:00 AM:: Morning Break
10:00 AM - 11:30 AM:: *Session 2:* _Operating Twelve-Factor Apps with Cloud Foundry_
11:30 PM - 12:30 PM:: Lunch
12:30 PM - 3:00 PM:: *Session 3:* _Microservices with Polyglot Persistence: Part One_
3:00 PM - 3:30 PM:: Afternoon Break
3:30 PM - 5:00 PM:: *Session 4:* _Microservices with Polyglot Persistence: Part Two_
